- name: "Reload systemd"
  command: systemctl daemon-reload
  tags: ['consul']

- name: "Restart consul"
  service:
    name: consul
    state: restarted
  when: not consul_do_not_start_immediately
  tags: ['consul']
